version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging into ECR
            - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 022499048865.dkr.ecr.eu-west-2.amazonaws.com
    build:
        commands:
            - echo Building Docker Images
            - docker build -t teo-counter-new .
            - docker tag teo-counter-new:latest 022499048865.dkr.ecr.eu-west-2.amazonaws.com/teo-counter-new:latest
    post_build:
        commands:
            - echo Pushing Docker image to ECR...
            - docker push 022499048865.dkr.ecr.eu-west-2.amazonaws.com/teo-counter-new:latest
            - echo Create imagedefinitions.json
            -printf '[{"name":"counter', "imageUri":"%s"}]' 022499048865.dkr.ecr.eu-west-2.amazonaws.com/teo-counter-new:latest > imagedefinitions.json
artifacts:
    files:
        - '**/*'
        - imagedefinitions.json
